server:
  port: 8080
  servlet:
    context-path: /universityAccessManagementSystem

# 数据库的配置信息
spring:
  datasource:
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.93.77.78:3306/universityAccessManagementSystem?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: sxf010629
    type: com.zaxxer.hikari.HikariDataSource

  redis:
    database: 1 #redis数据库索引，默认为0
    host: 47.93.77.78 #redis服务器地址
    port: 6379 #redis服务器连接端口
    password: sxf010629 #redis服务器连接密码，默认为null

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: edu.sau.universityaccessmanagementsystem.entity
  #开启驼峰命名转换
  configuration:
    useGeneratedKeys: true
    mapUnderscoreToCamelCase: true

